name: "Approve Issue"
description: "Approve the issue"
inputs:
  url:
    description: "The Bytebase URL. Example: https://bytebase.example.com"
    required: true
  token:
    description: "The API token obtained from bytebase/login action"
    required: true
  project-id:
    description: "The project ID. Example: example"
    required: true
  issue-uid:
    description: "The issue UID to approve. Example: 42"
    required: true
  comment:
    description: "The comment to add to the issue"
runs:
  using: "node20"
  main: "dist/index.js"
