name: "Login"
description: "Login to Bytebase and obtain an API token"
inputs:
  url:
    description: "The Bytebase URL. Example: https://bytebase.example.com"
    required: true
  service-account:
    description: "The service account to use for authentication"
    required: true
  service-account-key:
    description: "The service account key to use for authentication"
    required: true
outputs:
  token:
    description: "The API token obtained from bytebase/login action"
runs:
  using: "node20"
  main: "dist/index.js"
